// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ButtonGroup: typeof import('./components/ButtonGroup.vue')['default']
    DateSwitch: typeof import('./components/DateSwitch.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    InnerLayout: typeof import('./components/InnerLayout.vue')['default']
    SecondLayer: typeof import('./components/SecondLayer.vue')['default']
    TableFeature: typeof import('./components/TableFeature.vue')['default']
  }
}

export { }
